# Generated by Django 4.1.7 on 2023-02-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addCustomer',
            new_name='addCustomerModel',
        ),
    ]
