# Generated by Django 4.1.7 on 2023-02-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0003_customernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernumber',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
