# Generated by Django 4.1.7 on 2023-02-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0004_alter_customernumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomermodel',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='child_001.customernumber'),
        ),
    ]
