# Generated by Django 4.1.7 on 2023-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0005_addcustomermodel_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustomermodel',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='addcustomermodel',
            name='custid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerNumber',
        ),
    ]
