# Generated by Django 4.1.7 on 2023-02-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0006_remove_addcustomermodel_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustomermodel',
            name='custid',
        ),
    ]
