# Generated by Django 4.1.7 on 2023-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0007_remove_addcustomermodel_custid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomermodel',
            name='userid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
