# Generated by Django 4.1.7 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0008_addcustomermodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewBillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_for_the_month', models.CharField(blank=True, max_length=100, null=True)),
                ('current_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('total_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_per_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('final_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
